package dev.placeprep.mobile.ui

object MobileStrings {

    fun get(key: String, lang: String): String {
        val map = when (lang) {
            "ta" -> TAMIL
            "hi" -> HINDI
            else -> ENGLISH
        }
        return map[key] ?: ENGLISH[key] ?: key
    }

    private val ENGLISH = mapOf(
        "app_title" to "PlacePrep",
        "tagline" to "Discipline builds systems.",
        "chamber" to "Chamber",
        "tasks" to "Tasks",
        "architect" to "Architect",
        "assessments" to "Assessments",
        "coding" to "Coding Lab",
        "progress" to "Progress",
        "mentor" to "Mentor",
        "settings" to "Settings",
        "command_chamber" to "Command Chamber",
        "today_work" to "Today's Execution",
        "next_best_action" to "Next Best Action",
        "tasks_completed" to "Tasks Done",
        "minutes_invested" to "Minutes",
        "readiness_score" to "Readiness",
        "streak_days" to "Day Streak",
        "coach_me_through_it" to "Coach me through it",
        "unblock_now" to "Unblock with Coach",
        "blocked_label" to "Where are you blocked?",
        "topic_label" to "Problem or Topic",
        "hint_label" to "HINT",
        "approach_label" to "APPROACH PATH",
        "search_keywords" to "SEARCH KEYWORDS",
        "similar_problems" to "SIMILAR PROBLEMS",
        "evaluate_performance" to "Daily Performance Review",
        "reflections_label" to "Evening Reflection / Notes",
        "focus_score" to "Focus Score (1-10)",
        "submit_review" to "Submit Evaluation",
        "quick_add_task" to "Add Task",
        "create_task" to "Create Task",
        "task_title" to "Task Title",
        "estimated_minutes" to "Estimated Minutes",
        "category" to "Category",
        "priority" to "Priority",
        "cancel" to "Cancel",
        "save" to "Save",
        "sign_in" to "Sign In",
        "sign_out" to "Sign Out",
        "create_account" to "Create Account",
        "notifications" to "Notifications",
        "push_notifications" to "Android Push Notifications",
        "email_notifications" to "Email Alerts",
        "test_notification" to "Send Test Notification",
        "permission_granted" to "Permission Granted",
        "permission_denied" to "Permission Denied",
        "grant_permission" to "Grant Permission",
        "language" to "Interface Language",
        "offline_notice" to "Offline Mode — Changes will sync when connected",
        "empty_tasks" to "No tasks scheduled for today.",
        "generate_plan" to "Generate Plan",
        "roadmap_weeks" to "Roadmap Weeks",
        "send_message" to "Send Message",
        "clear_chat" to "Clear History",
        "search_problems" to "Search LeetCode catalog...",
        "all" to "All",
        "pending" to "Pending",
        "completed" to "Completed",
    )

    private val TAMIL = mapOf(
        "app_title" to "PlacePrep",
        "tagline" to "ஒழுக்கம் அமைப்புகளை உருவாக்குகிறது.",
        "chamber" to "அறை",
        "tasks" to "பணிகள்",
        "architect" to "திட்டம்",
        "assessments" to "மதிப்பீடுகள்",
        "coding" to "கோடிங் லேப்",
        "progress" to "முன்னேற்றம்",
        "mentor" to "ஆலோசகர்",
        "settings" to "அமைப்புகள்",
        "command_chamber" to "கட்டளை அறை",
        "today_work" to "இன்றைய பணிகள்",
        "next_best_action" to "அடுத்த சிறந்த செயல்",
        "tasks_completed" to "முடிந்த பணிகள்",
        "minutes_invested" to "நிமிடங்கள்",
        "readiness_score" to "தயார்நிலை",
        "streak_days" to "தொடர்ச்சி",
        "coach_me_through_it" to "பயிற்சியாளரிடம் உதவி பெறு",
        "unblock_now" to "உடனடி வழிகாட்டல்",
        "blocked_label" to "எங்கே குழப்பம்?",
        "topic_label" to "தலைப்பு அல்லது கணக்கு",
        "hint_label" to "குறிப்பு",
        "approach_label" to "அணுகுமுறை படிகள்",
        "search_keywords" to "தேடல் சொற்கள்",
        "similar_problems" to "தொடர்புடைய கணக்குகள்",
        "evaluate_performance" to "தினசரி மதிப்பாய்வு",
        "reflections_label" to "இன்றைய குறிப்புகள்",
        "focus_score" to "கவன மதிப்பெண் (1-10)",
        "submit_review" to "மதிப்பாய்வு சமர்ப்பி",
        "quick_add_task" to "பணி சேர்க்க",
        "create_task" to "பணி உருவாக்கு",
        "task_title" to "பணியின் தலைப்பு",
        "estimated_minutes" to "மதிப்பிடப்பட்ட நிமிடங்கள்",
        "category" to "பிரிவு",
        "priority" to "முன்னுரிமை",
        "cancel" to "ரத்து செய்",
        "save" to "சேமி",
        "sign_in" to "உள்நுழைக",
        "sign_out" to "வெளியேறு",
        "create_account" to "கணக்கு தொடங்க",
        "notifications" to "அறிவிப்புகள்",
        "push_notifications" to "Android நேரடி அறிவிப்புகள்",
        "email_notifications" to "மின்னஞ்சல் அறிவிப்புகள்",
        "test_notification" to "சோதனை அறிவிப்பு அனுப்பு",
        "permission_granted" to "அனுமதி வழங்கப்பட்டது",
        "permission_denied" to "அனுமதி மறுக்கப்பட்டது",
        "grant_permission" to "அனுமதி வழங்கவும்",
        "language" to "மொழி",
        "offline_notice" to "இணைப்பற்ற நிலை — இணையம் கிடைத்ததும் ஒத்திசைக்கப்படும்",
        "empty_tasks" to "இன்றைக்கு பணிகள் எதுவும் திட்டமிடப்படவில்லை.",
        "generate_plan" to "திட்டம் உருவாக்கு",
        "roadmap_weeks" to "வாராந்திர வரைபடம்",
        "send_message" to "செய்தி அனுப்பு",
        "clear_chat" to "வரலாற்றை அழி",
        "search_problems" to "LeetCode கணக்குகளைத் தேடு...",
        "all" to "அனைத்தும்",
        "pending" to "நிலுவையில்",
        "completed" to "முடிந்தது",
    )

    private val HINDI = mapOf(
        "app_title" to "PlacePrep",
        "tagline" to "अनुशासन से ही व्यवस्था बनती है.",
        "chamber" to "कमांड कक्ष",
        "tasks" to "कार्य",
        "architect" to "योजना",
        "assessments" to "मूल्यांकन",
        "coding" to "कोडिंग लैब",
        "progress" to "प्रगति",
        "mentor" to "मार्गदर्शक",
        "settings" to "सेटिंग्स",
        "command_chamber" to "कमांड कक्ष",
        "today_work" to "आज का निष्पादन",
        "next_best_action" to "अगला सबसे महत्वपूर्ण कार्य",
        "tasks_completed" to "पूर्ण कार्य",
        "minutes_invested" to "मिनट",
        "readiness_score" to "तैयारी स्तर",
        "streak_days" to "स्ट्रीक",
        "coach_me_through_it" to "कोच से मदद लें",
        "unblock_now" to "समाधान मार्गदर्शन",
        "blocked_label" to "कहाँ अटके हैं?",
        "topic_label" to "समस्या या विषय",
        "hint_label" to "संकेत",
        "approach_label" to "समाधान दृष्टिकोण",
        "search_keywords" to "खोज कीवर्ड",
        "similar_problems" to "समान प्रश्न",
        "evaluate_performance" to "दैनिक प्रदर्शन समीक्षा",
        "reflections_label" to "शाम का विचार / नोट्स",
        "focus_score" to "फोकस स्कोर (1-10)",
        "submit_review" to "समीक्षा सबमिट करें",
        "quick_add_task" to "कार्य जोड़ें",
        "create_task" to "नया कार्य बनाएं",
        "task_title" to "कार्य शीर्षक",
        "estimated_minutes" to "अनुमानित मिनट",
        "category" to "श्रेणी",
        "priority" to "प्राथमिकता",
        "cancel" to "रद्द करें",
        "save" to "सहेजें",
        "sign_in" to "साइन इन करें",
        "sign_out" to "साइन आउट",
        "create_account" to "खाता बनाएं",
        "notifications" to "सूचनाएं",
        "push_notifications" to "Android पुश नोटिफिकेशन",
        "email_notifications" to "ईमेल सूचनाएं",
        "test_notification" to "टेस्ट नोटिफिकेशन भेजें",
        "permission_granted" to "अनुमति प्राप्त",
        "permission_denied" to "अनुमति अस्वीकृत",
        "grant_permission" to "अनुमति दें",
        "language" to "भाषा",
        "offline_notice" to "ऑफ़लाइन मोड — कनेक्शन बहाल होने पर सिंक होगा",
        "empty_tasks" to "आज के लिए कोई कार्य निर्धारित नहीं है.",
        "generate_plan" to "योजना बनाएं",
        "roadmap_weeks" to "सप्ताहिक रोडमैप",
        "send_message" to "संदेश भेजें",
        "clear_chat" to "इतिहास मिटाएं",
        "search_problems" to "LeetCode प्रश्न खोजें...",
        "all" to "सभी",
        "pending" to "लंबित",
        "completed" to "पूर्ण",
    )
}
