export const PREP_TOPICS = [
  "Arrays",
  "Strings",
  "Linked Lists",
  "Stacks",
  "Queues",
  "Binary Trees",
  "Binary Search Trees",
  "Graphs",
  "Dynamic Programming",
  "Greedy Algorithms",
  "Recursion",
  "Backtracking",
  "Object-Oriented Programming",
  "System Design",
  "DBMS",
  "Operating Systems",
  "SQL",
  "Python",
  "Statistics",
  "Pandas",
  "Data Visualization",
  "Excel",
  "Power BI",
  "Tableau",
  "ETL",
  "Data Warehousing",
  "Data Modeling",
  "Spark",
  "Airflow",
  "Machine Learning",
];

export const TARGET_ROLES = [
  "Backend Engineer",
  "Frontend Engineer",
  "Full Stack Engineer",
  "Software Engineer",
  "SDE Intern",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
];
