export type UiLanguage = "english" | "tamil" | "hindi";

export const UI_LANGUAGE_STORAGE_KEY = "placeprep.ui-language";

export const UI_LANGUAGE_OPTIONS: Array<{
  value: UiLanguage;
  label: string;
  nativeLabel: string;
  htmlLang: string;
}> = [
  { value: "english", label: "English", nativeLabel: "English", htmlLang: "en" },
  { value: "tamil", label: "Tamil", nativeLabel: "தமிழ்", htmlLang: "ta" },
  { value: "hindi", label: "Hindi", nativeLabel: "हिन्दी", htmlLang: "hi" },
];

type TranslationTable = Record<string, string>;

const TAMIL_TRANSLATIONS: TranslationTable = {
  "Loading workspace": "பணியிடத்தை ஏற்றுகிறது",
  "Restoring your PlacePrep session.": "உங்கள் PlacePrep அமர்வை மீட்டெடுக்கிறது.",
  "Navigate": "வழிசெல்",
  "Signals": "சிக்னல்கள்",
  "AI status": "AI நிலை",
  "Live": "நேரலை",
  "Fallback": "மாற்று நிலை",
  "checking": "சரிபார்க்கிறது",
  "offline": "ஆஃப்லைன்",
  "Command Chamber": "கட்டளை அறை",
  "Prep Architect": "தயாரிப்பு வடிவமைப்பாளர்",
  "Assessments": "மதிப்பீடுகள்",
  "Tasks": "பணிகள்",
  "Progress": "முன்னேற்றம்",
  "Nocturne Mentor": "இரவு வழிகாட்டி",
  "Settings": "அமைப்புகள்",
  "Profile": "சுயவிவரம்",
  "Clock. Focus. Execute.": "நேரம். கவனம். செயல்பாடு.",
  "Map. Practice. Recall.": "வரைபடம். பயிற்சி. நினைவு.",
  "Queue. Strike. Clear.": "வரிசை. செயல். முடித்தல்.",
  "Probe. Measure. Adapt.": "சோதனை. அளவீடு. மாற்றம்.",
  "Signal. Drift. Recover.": "சிக்னல். சிதறல். மீட்பு.",
  "Presence. Craft. Proof.": "அடையாளம். வடிவமைப்பு. ஆதாரம்.",
  "Tune. Save. Return.": "சீரமை. சேமி. திரும்பு.",
  "Ask. Refine. Advance.": "கேள். திருத்து. முன்னேறு.",
  "How it works": "இது எப்படி வேலை செய்கிறது",
  "AI live": "AI செயல்பாட்டில்",
  "Checking": "சரிபார்க்கிறது",
  "Demo mode": "டெமோ நிலை",
  "Open navigation": "வழிசெலுத்தலைத் திற",
  "Open profile menu": "சுயவிவர மெனுவைத் திற",
  "Logout": "வெளியேறு",
  "Observer access": "பார்வையாளர் அணுகல்",
  "Set username": "பயனர்பெயர் அமை",
  "Architect sync": "வடிவமைப்பு ஒத்திசைவு",
  "Refresh": "புதுப்பி",
  "Open Prep Architect": "தயாரிப்பு வடிவமைப்பாளரைத் திற",
  "Readiness": "தயார்நிலை",
  "Consistency": "தொடர்ச்சித்தன்மை",
  "Execution": "செயல்பாடு",
  "Idle": "செயலற்றது",
  "Active": "செயலில்",
  "Today's tasks": "இன்றைய பணிகள்",
  "No tasks scheduled": "இன்றைக்கு பணிகள் இல்லை",
  "Generate a coach plan to build today's work around your actual weak areas.": "உங்கள் உண்மையான பலவீனங்களை அடிப்படையாகக் கொண்டு இன்றைய பணியை உருவாக்க பயிற்சியாளர் திட்டத்தை உருவாக்குங்கள்.",
  "Coach Console": "பயிற்சியாளர் கட்டுப்பாடு",
  "Personal planning, rescue, and daily review.": "தனிப்பட்ட திட்டமிடல், உதவி, தினசரி மதிப்பாய்வு.",
  "Generate Today's Plan": "இன்றைய திட்டத்தை உருவாக்கு",
  "Generate and deploy plan": "திட்டத்தை உருவாக்கி செயல்படுத்து",
  "Generating plan...": "திட்டம் உருவாக்கப்படுகிறது...",
  "I'm Stuck": "நான் சிக்கியிருக்கிறேன்",
  "Problem name or topic": "பிரச்சினை பெயர் அல்லது தலைப்பு",
  "What have you tried? Where exactly are you blocked?": "நீங்கள் என்ன முயன்றீர்கள்? எங்கே தடை ஏற்பட்டுள்ளது?",
  "Coach me through it": "எனக்கு வழிகாட்டு",
  "Evaluate Today": "இன்றையதை மதிப்பிடு",
  "Run daily evaluation": "தினசரி மதிப்பீட்டை இயக்கு",
  "Productivity score": "உற்பத்தித் திறன் மதிப்பெண்",
  "Weak areas": "பலவீனப் பகுதிகள்",
  "Fix tomorrow": "நாளை திருத்தம்",
  "Hint": "குறிப்பு",
  "Approach": "அணுகுமுறை",
  "Practice Next": "அடுத்த பயிற்சி",
  "Control identity, links, and system behavior.": "அடையாளம், இணைப்புகள், மற்றும் அமைப்பு நடத்தை கட்டுப்படுத்து.",
  "Account": "கணக்கு",
  "Username and profile": "பயனர்பெயர் மற்றும் சுயவிவரம்",
  "Display name": "காட்சி பெயர்",
  "Username": "பயனர்பெயர்",
  "Target role": "இலக்கு பங்கு",
  "Placement date": "பிளேஸ்மெண்ட் தேதி",
  "Preferred language": "விருப்ப மொழி",
  "Save account settings": "கணக்கு அமைப்புகளை சேமி",
  "Saving...": "சேமிக்கிறது...",
  "Notifications": "அறிவிப்புகள்",
  "Strict signals. No fluff.": "துல்லியமான சிக்னல்கள். தேவையற்றது இல்லை.",
  "Daily reminders, pending task pressure, streak warnings, deadline urgency, and sharp motivation.": "தினசரி நினைவூட்டல்கள், நிலுவைப் பணிச் சிக்னல்கள், தொடர்ச்சி எச்சரிக்கை, கடைசி தேதி அவசரம், தெளிவான ஊக்கம்.",
  "Browser permission": "உலாவி அனுமதி",
  "Strict notifications": "கடுமையான அறிவிப்புகள்",
  "Master switch for all mentor reminders.": "அனைத்து வழிகாட்டி நினைவூட்டல்களுக்கான முதன்மை சுவிட்ச்.",
  "Email prompts": "மின்னஞ்சல் நினைவூட்டல்கள்",
  "Background browser alerts": "பின்னணி உலாவி எச்சரிக்கைகள்",
  "Save notification settings": "அறிவிப்பு அமைப்புகளை சேமி",
  "Sync now": "இப்போது ஒத்திசை",
  "Syncing...": "ஒத்திசைக்கிறது...",
  "Mark all read": "அனைத்தையும் படித்ததாக குறி",
  "Recent signals": "சமீபத்திய சிக்னல்கள்",
  "Latest pressure from the system.": "அமைப்பிலிருந்து சமீபத்திய அழுத்தம்.",
  "Unread": "படிக்காதது",
  "Read": "படிக்கப்பட்டது",
  "Build a learning engine around what you know and what you still need.": "நீங்கள் அறிந்ததும் இன்னும் கற்றுக்கொள்ள வேண்டியதும் அடிப்படையாக கற்றல் இயந்திரத்தை உருவாக்குங்கள்.",
  "Input system": "உள்ளீட்டு அமைப்பு",
  "Editable, tag-based planning": "திருத்தக்கூடிய, குறிச்சொல் அடிப்படையிலான திட்டமிடல்",
  "Generate Plan": "திட்டத்தை உருவாக்கு",
  "Edit Plan": "திட்டத்தைத் திருத்து",
  "Regenerate Plan": "திட்டத்தை மீண்டும் உருவாக்கு",
  "Update Plan": "திட்டத்தை புதுப்பி",
  "What do you know?": "நீங்கள் என்ன அறிவீர்கள்?",
  "What do you want to learn?": "நீங்கள் என்ன கற்றுக்கொள்ள விரும்புகிறீர்கள்?",
  "Search or add known topics": "அறிந்த தலைப்புகளை தேடு அல்லது சேர்",
  "Search or add target topics": "இலக்கு தலைப்புகளை தேடு அல்லது சேர்",
  "Time per day": "ஒரு நாளுக்கு நேரம்",
  "Plan duration": "திட்ட காலம்",
  "Plan language": "திட்ட மொழி",
  "Choose a role": "ஒரு பங்கைத் தேர்வு செய்",
  "Choose a language": "ஒரு மொழியைத் தேர்வு செய்",
  "Version history": "பதிப்பு வரலாறு",
  "Clear": "அழி",
  "Current plan": "தற்போதைய திட்டம்",
  "Mentor line": "வழிகாட்டி வரி",
  "Roadmap": "சாலை வரைபடம்",
  "Study stack": "படிப்பு தொகுப்பு",
  "Flashcards": "ஃபிளாஷ்கார்டுகள்",
  "Assessments stay role-aware.": "மதிப்பீடுகள் பங்கு சார்ந்தவையாக இருக்கும்.",
  "Assessment Builder": "மதிப்பீட்டு உருவாக்கி",
  "MCQ sprint": "MCQ வேகப் பயிற்சி",
  "Fill in the blanks": "காலியிடங்களை நிரப்புக",
  "Short programming": "குறுகிய நிரலாக்கம்",
  "Daily focus": "தினசரி கவனம்",
  "Weekly sweep": "வாராந்திர மதிப்பீடு",
  "Assessment duration": "மதிப்பீட்டு காலம்",
  "Start assessment": "மதிப்பீட்டை தொடங்கு",
  "Submit assessment": "மதிப்பீட்டை சமர்ப்பி",
  "Regenerate": "மீண்டும் உருவாக்கு",
  "Current assessment": "தற்போதைய மதிப்பீடு",
  "Recent assessments": "சமீபத்திய மதிப்பீடுகள்",
  "No assessment started yet.": "இன்னும் மதிப்பீடு தொடங்கவில்லை.",
  "Mission Control": "பணி கட்டுப்பாடு",
  "Details": "விவரங்கள்",
  "Hide details": "விவரங்களை மறை",
  "Open reference": "குறிப்பு இணைப்பைத் திற",
  "Resume intelligence": "ரெச்யூமே பகுப்பாய்வு",
  "Job-specific ATS check": "வேலை விவரத்திற்கான ATS சோதனை",
  "Paste job description": "வேலை விவரத்தை ஒட்டு",
  "Score against JD": "JD அடிப்படையில் மதிப்பெண் கணக்கு",
};

const HINDI_TRANSLATIONS: TranslationTable = {
  "Loading workspace": "वर्कस्पेस लोड हो रहा है",
  "Restoring your PlacePrep session.": "आपका PlacePrep सत्र बहाल हो रहा है.",
  "Navigate": "नेविगेट",
  "Signals": "सिग्नल",
  "AI status": "AI स्थिति",
  "Live": "लाइव",
  "Fallback": "फॉलबैक",
  "checking": "जांच रहा है",
  "offline": "ऑफलाइन",
  "Command Chamber": "कमांड चेंबर",
  "Prep Architect": "प्रेप आर्किटेक्ट",
  "Assessments": "मूल्यांकन",
  "Tasks": "कार्य",
  "Progress": "प्रगति",
  "Nocturne Mentor": "नॉक्टर्न मेंटर",
  "Settings": "सेटिंग्स",
  "Profile": "प्रोफ़ाइल",
  "Clock. Focus. Execute.": "समय. ध्यान. निष्पादन.",
  "Map. Practice. Recall.": "मैप. अभ्यास. याद.",
  "Queue. Strike. Clear.": "कतार. वार. साफ़.",
  "Probe. Measure. Adapt.": "जांच. माप. सुधार.",
  "Signal. Drift. Recover.": "सिग्नल. भटकाव. रिकवरी.",
  "Presence. Craft. Proof.": "उपस्थिति. निर्माण. प्रमाण.",
  "Tune. Save. Return.": "ट्यून. सेव. वापसी.",
  "Ask. Refine. Advance.": "पूछें. सुधारें. आगे बढ़ें.",
  "How it works": "यह कैसे काम करता है",
  "AI live": "AI लाइव",
  "Checking": "जांच रहा है",
  "Demo mode": "डेमो मोड",
  "Open navigation": "नेविगेशन खोलें",
  "Open profile menu": "प्रोफ़ाइल मेनू खोलें",
  "Logout": "लॉगआउट",
  "Observer access": "ऑब्ज़र्वर एक्सेस",
  "Architect sync": "आर्किटेक्ट सिंक",
  "Refresh": "रिफ्रेश",
  "Open Prep Architect": "प्रेप आर्किटेक्ट खोलें",
  "Readiness": "तैयारी",
  "Consistency": "निरंतरता",
  "Execution": "निष्पादन",
  "Idle": "निष्क्रिय",
  "Active": "सक्रिय",
  "Today's tasks": "आज के कार्य",
  "No tasks scheduled": "आज कोई कार्य तय नहीं",
  "Generate a coach plan to build today's work around your actual weak areas.": "अपने वास्तविक कमजोर क्षेत्रों के आधार पर आज का काम बनाने के लिए कोच प्लान जनरेट करें.",
  "Coach Console": "कोच कंसोल",
  "Personal planning, rescue, and daily review.": "व्यक्तिगत योजना, सहायता, और दैनिक समीक्षा.",
  "Generate Today's Plan": "आज का प्लान जनरेट करें",
  "Generate and deploy plan": "प्लान जनरेट और लागू करें",
  "Generating plan...": "प्लान बन रहा है...",
  "I'm Stuck": "मैं अटक गया हूं",
  "Problem name or topic": "समस्या का नाम या टॉपिक",
  "What have you tried? Where exactly are you blocked?": "आपने क्या कोशिश की? आप कहां अटके हैं?",
  "Coach me through it": "मुझे इसमें गाइड करें",
  "Evaluate Today": "आज का मूल्यांकन",
  "Run daily evaluation": "दैनिक मूल्यांकन चलाएं",
  "Productivity score": "उत्पादकता स्कोर",
  "Weak areas": "कमजोर क्षेत्र",
  "Fix tomorrow": "कल सुधारें",
  "Hint": "संकेत",
  "Approach": "तरीका",
  "Practice Next": "अगला अभ्यास",
  "Control identity, links, and system behavior.": "पहचान, लिंक, और सिस्टम व्यवहार नियंत्रित करें.",
  "Account": "खाता",
  "Username and profile": "यूज़रनेम और प्रोफ़ाइल",
  "Display name": "डिस्प्ले नाम",
  "Username": "यूज़रनेम",
  "Target role": "लक्ष्य भूमिका",
  "Placement date": "प्लेसमेंट तारीख",
  "Preferred language": "पसंदीदा भाषा",
  "Save account settings": "खाता सेटिंग्स सेव करें",
  "Saving...": "सेव हो रहा है...",
  "Notifications": "सूचनाएं",
  "Strict signals. No fluff.": "सख्त सिग्नल. कोई फालतू नहीं.",
  "Daily reminders, pending task pressure, streak warnings, deadline urgency, and sharp motivation.": "दैनिक रिमाइंडर, लंबित कार्य दबाव, स्ट्रीक चेतावनी, डेडलाइन अर्जेंसी, और साफ़ मोटिवेशन.",
  "Browser permission": "ब्राउज़र अनुमति",
  "Strict notifications": "सख्त सूचनाएं",
  "Master switch for all mentor reminders.": "सभी मेंटर रिमाइंडर के लिए मुख्य स्विच.",
  "Email prompts": "ईमेल संकेत",
  "Background browser alerts": "बैकग्राउंड ब्राउज़र अलर्ट",
  "Save notification settings": "सूचना सेटिंग्स सेव करें",
  "Sync now": "अभी सिंक करें",
  "Syncing...": "सिंक हो रहा है...",
  "Mark all read": "सबको पढ़ा हुआ करें",
  "Recent signals": "हाल के सिग्नल",
  "Latest pressure from the system.": "सिस्टम से नवीनतम दबाव.",
  "Unread": "अपठित",
  "Read": "पढ़ा हुआ",
  "Build a learning engine around what you know and what you still need.": "जो आप जानते हैं और जो अभी सीखना है, उसके आधार पर लर्निंग इंजन बनाएं.",
  "Input system": "इनपुट सिस्टम",
  "Editable, tag-based planning": "संपादन योग्य, टैग आधारित योजना",
  "Generate Plan": "प्लान जनरेट करें",
  "Edit Plan": "प्लान संपादित करें",
  "Regenerate Plan": "प्लान दोबारा बनाएं",
  "Update Plan": "प्लान अपडेट करें",
  "What do you know?": "आप क्या जानते हैं?",
  "What do you want to learn?": "आप क्या सीखना चाहते हैं?",
  "Search or add known topics": "ज्ञात टॉपिक खोजें या जोड़ें",
  "Search or add target topics": "लक्ष्य टॉपिक खोजें या जोड़ें",
  "Time per day": "हर दिन समय",
  "Plan duration": "प्लान अवधि",
  "Plan language": "प्लान भाषा",
  "Choose a role": "भूमिका चुनें",
  "Choose a language": "भाषा चुनें",
  "Version history": "वर्ज़न इतिहास",
  "Clear": "साफ़ करें",
  "Current plan": "वर्तमान प्लान",
  "Mentor line": "मेंटर लाइन",
  "Roadmap": "रोडमैप",
  "Study stack": "स्टडी स्टैक",
  "Flashcards": "फ्लैशकार्ड",
  "Assessments stay role-aware.": "मूल्यांकन भूमिका के अनुसार रहेंगे.",
  "Assessment Builder": "मूल्यांकन बिल्डर",
  "MCQ sprint": "MCQ स्प्रिंट",
  "Fill in the blanks": "रिक्त स्थान भरें",
  "Short programming": "छोटी प्रोग्रामिंग",
  "Daily focus": "दैनिक फोकस",
  "Weekly sweep": "साप्ताहिक समीक्षा",
  "Assessment duration": "मूल्यांकन अवधि",
  "Start assessment": "मूल्यांकन शुरू करें",
  "Submit assessment": "मूल्यांकन जमा करें",
  "Regenerate": "दोबारा बनाएं",
  "Current assessment": "वर्तमान मूल्यांकन",
  "Recent assessments": "हाल के मूल्यांकन",
  "No assessment started yet.": "अभी कोई मूल्यांकन शुरू नहीं हुआ.",
  "Mission Control": "मिशन कंट्रोल",
  "Details": "विवरण",
  "Hide details": "विवरण छिपाएं",
  "Open reference": "संदर्भ खोलें",
  "Resume intelligence": "रिज़्यूमे इंटेलिजेंस",
  "Job-specific ATS check": "जॉब-विशिष्ट ATS जांच",
  "Paste job description": "जॉब विवरण पेस्ट करें",
  "Score against JD": "JD के अनुसार स्कोर करें",
};

const FRAGMENT_TRANSLATIONS: Record<Exclude<UiLanguage, "english">, TranslationTable> = {
  tamil: {
    " is active": " செயலில் உள்ளது",
    " is synced into the system.": " அமைப்பில் ஒத்திசைக்கப்பட்டுள்ளது.",
    "No active architect plan yet.": "இன்னும் செயலில் உள்ள வடிவமைப்பு திட்டம் இல்லை.",
    "Build one": "ஒன்றை உருவாக்குங்கள்",
    "month": "மாதம்",
    "months": "மாதங்கள்",
    "hrs": "மணி",
    "hr": "மணி",
    "Retry": "மீண்டும் முயற்சி",
    "Cancel": "ரத்து செய்",
    "Delete selected": "தேர்ந்தெடுத்ததை நீக்கு",
    "Use version": "இந்த பதிப்பை பயன்படுத்து",
  },
  hindi: {
    " is active": " सक्रिय है",
    " is synced into the system.": " सिस्टम में सिंक है.",
    "No active architect plan yet.": "अभी कोई सक्रिय आर्किटेक्ट प्लान नहीं है.",
    "Build one": "एक बनाएं",
    "month": "माह",
    "months": "माह",
    "hrs": "घंटे",
    "hr": "घंटा",
    "Retry": "फिर कोशिश करें",
    "Cancel": "रद्द करें",
    "Delete selected": "चयनित हटाएं",
    "Use version": "इस वर्ज़न का उपयोग करें",
  },
};

const TRANSLATIONS: Record<Exclude<UiLanguage, "english">, TranslationTable> = {
  tamil: TAMIL_TRANSLATIONS,
  hindi: HINDI_TRANSLATIONS,
};

export function normalizeUiLanguage(value: unknown): UiLanguage {
  const normalized = String(value || "").trim().toLowerCase();
  return normalized === "tamil" || normalized === "hindi" ? normalized : "english";
}

export function getUiLanguageOption(language: UiLanguage) {
  return UI_LANGUAGE_OPTIONS.find((option) => option.value === language) || UI_LANGUAGE_OPTIONS[0];
}

function preserveWhitespace(source: string, translated: string) {
  const leading = source.match(/^\s*/)?.[0] || "";
  const trailing = source.match(/\s*$/)?.[0] || "";
  return `${leading}${translated}${trailing}`;
}

export function translateUiText(value: string, language: UiLanguage) {
  if (language === "english") {
    return value;
  }

  const source = String(value ?? "");
  const trimmed = source.trim();

  if (!trimmed) {
    return source;
  }

  const table = TRANSLATIONS[language];
  const exact = table[trimmed];
  if (exact) {
    return preserveWhitespace(source, exact);
  }

  let translated = trimmed;
  const fragments = FRAGMENT_TRANSLATIONS[language];

  Object.entries(fragments).forEach(([english, localized]) => {
    translated = translated.split(english).join(localized);
  });

  return translated === trimmed ? source : preserveWhitespace(source, translated);
}
