export type UiLanguage = "english" | "tamil" | "hindi";

export const UI_LANGUAGE_STORAGE_KEY = "placeprep.ui-language";

export const UI_LANGUAGE_OPTIONS: Array<{
  value: UiLanguage;
  label: string;
  nativeLabel: string;
  htmlLang: string;
}> = [
  { value: "english", label: "English", nativeLabel: "English", htmlLang: "en" },
  { value: "tamil", label: "Tamil", nativeLabel: "தமிழ்", htmlLang: "ta" },
  { value: "hindi", label: "Hindi", nativeLabel: "हिन्दी", htmlLang: "hi" },
];

type TranslationTable = Record<string, string>;

const TAMIL_TRANSLATIONS: TranslationTable = {
  "Loading workspace": "பணியிடத்தை ஏற்றுகிறது",
  "Restoring your PlacePrep session.": "உங்கள் PlacePrep அமர்வை மீட்டெடுக்கிறது.",
  "Navigate": "வழிசெல்",
  "Signals": "சிக்னல்கள்",
  "AI status": "AI நிலை",
  "Live": "நேரலை",
  "Fallback": "மாற்று நிலை",
  "checking": "சரிபார்க்கிறது",
  "offline": "ஆஃப்லைன்",
  "Command Chamber": "கட்டளை அறை",
  "Prep Architect": "தயாரிப்பு வடிவமைப்பாளர்",
  "Assessments": "மதிப்பீடுகள்",
  "Tasks": "பணிகள்",
  "Progress": "முன்னேற்றம்",
  "Nocturne Mentor": "இரவு வழிகாட்டி",
  "Settings": "அமைப்புகள்",
  "Profile": "சுயவிவரம்",
  "Clock. Focus. Execute.": "நேரம். கவனம். செயல்பாடு.",
  "Map. Practice. Recall.": "வரைபடம். பயிற்சி. நினைவு.",
  "Queue. Strike. Clear.": "வரிசை. செயல். முடித்தல்.",
  "Probe. Measure. Adapt.": "சோதனை. அளவீடு. மாற்றம்.",
  "Signal. Drift. Recover.": "சிக்னல். சிதறல். மீட்பு.",
  "Presence. Craft. Proof.": "அடையாளம். வடிவமைப்பு. ஆதாரம்.",
  "Tune. Save. Return.": "சீரமை. சேமி. திரும்பு.",
  "Ask. Refine. Advance.": "கேள். திருத்து. முன்னேறு.",
  "How it works": "இது எப்படி வேலை செய்கிறது",
  "AI live": "AI செயல்பாட்டில்",
  "Checking": "சரிபார்க்கிறது",
  "Demo mode": "டெமோ நிலை",
  "Open navigation": "வழிசெலுத்தலைத் திற",
  "Open profile menu": "சுயவிவர மெனுவைத் திற",
  "Logout": "வெளியேறு",
  "Observer access": "பார்வையாளர் அணுகல்",
  "Set username": "பயனர்பெயர் அமை",
  "Architect sync": "வடிவமைப்பு ஒத்திசைவு",
  "Refresh": "புதுப்பி",
  "Open Prep Architect": "தயாரிப்பு வடிவமைப்பாளரைத் திற",
  "Readiness": "தயார்நிலை",
  "Consistency": "தொடர்ச்சித்தன்மை",
  "Execution": "செயல்பாடு",
  "Idle": "செயலற்றது",
  "Active": "செயலில்",
  "Today's tasks": "இன்றைய பணிகள்",
  "No tasks scheduled": "இன்றைக்கு பணிகள் இல்லை",
  "Generate a coach plan to build today's work around your actual weak areas.": "உங்கள் உண்மையான பலவீனங்களை அடிப்படையாகக் கொண்டு இன்றைய பணியை உருவாக்க பயிற்சியாளர் திட்டத்தை உருவாக்குங்கள்.",
  "Coach Console": "பயிற்சியாளர் கட்டுப்பாடு",
  "Personal planning, rescue, and daily review.": "தனிப்பட்ட திட்டமிடல், உதவி, தினசரி மதிப்பாய்வு.",
  "Generate Today's Plan": "இன்றைய திட்டத்தை உருவாக்கு",
  "Generate and deploy plan": "திட்டத்தை உருவாக்கி செயல்படுத்து",
  "Generating plan...": "திட்டம் உருவாக்கப்படுகிறது...",
  "I'm Stuck": "நான் சிக்கியிருக்கிறேன்",
  "Problem name or topic": "பிரச்சினை பெயர் அல்லது தலைப்பு",
  "What have you tried? Where exactly are you blocked?": "நீங்கள் என்ன முயன்றீர்கள்? எங்கே தடை ஏற்பட்டுள்ளது?",
  "Coach me through it": "எனக்கு வழிகாட்டு",
  "Evaluate Today": "இன்றையதை மதிப்பிடு",
  "Run daily evaluation": "தினசரி மதிப்பீட்டை இயக்கு",
  "Productivity score": "உற்பத்தித் திறன் மதிப்பெண்",
  "Weak areas": "பலவீனப் பகுதிகள்",
  "Fix tomorrow": "நாளை திருத்தம்",
  "Hint": "குறிப்பு",
  "Progressive Hint": "முற்போக்குக் குறிப்பு",
  "Approach": "அணுகுமுறை",
  "Approach Steps": "அணுகுமுறைப் படிகள்",
  "Practice Next": "அடுத்த பயிற்சி",
  "Recommended Practice": "பரிந்துரைக்கப்பட்ட பயிற்சி",
  "Search Keywords": "தேடல் சொற்கள்",
  "Rescue": "மீட்பு",
  "Plan": "திட்டம்",
  "Review": "மதிப்பாய்வு",
  "Analyzing problem...": "பிரச்சினையை ஆராய்கிறது...",
  "Next Best Action": "அடுத்த சிறந்த செயல்",
  "Focus Sprint": "கவனக் குவியல்",
  "Start 25m Focus Sprint": "25 நிமிட கவனக் குவியலைத் தொடங்கு",
  "Execution Summary": "செயல்பாட்டு சுருக்கம்",
  "No tasks scheduled for today": "இன்றைக்கு எந்தப் பணியும் திட்டமிடப்படவில்லை",
  "Hold the line until placement day.": "பிளேஸ்மெண்ட் நாள் வரை நிலைகுலையாமல் இருங்கள்.",
  "Control identity, links, and system behavior.": "அடையாளம், இணைப்புகள், மற்றும் அமைப்பு நடத்தை கட்டுப்படுத்து.",
  "Account": "கணக்கு",
  "Username and profile": "பயனர்பெயர் மற்றும் சுயவிவரம்",
  "Display name": "காட்சி பெயர்",
  "Username": "பயனர்பெயர்",
  "Target role": "இலக்கு பங்கு",
  "Placement date": "பிளேஸ்மெண்ட் தேதி",
  "Preferred language": "விருப்ப மொழி",
  "Save account settings": "கணக்கு அமைப்புகளை சேமி",
  "Saving...": "சேமிக்கிறது...",
  "Notifications": "அறிவிப்புகள்",
  "Strict signals. No fluff.": "துல்லியமான சிக்னல்கள். தேவையற்றது இல்லை.",
  "Daily reminders, pending task pressure, streak warnings, deadline urgency, and sharp motivation.": "தினசரி நினைவூட்டல்கள், நிலுவைப் பணிச் சிக்னல்கள், தொடர்ச்சி எச்சரிக்கை, கடைசி தேதி அவசரம், தெளிவான ஊக்கம்.",
  "Browser permission": "உலாவி அனுமதி",
  "Strict notifications": "கடுமையான அறிவிப்புகள்",
  "Master switch for all mentor reminders.": "அனைத்து வழிகாட்டி நினைவூட்டல்களுக்கான முதன்மை சுவிட்ச்.",
  "Email prompts": "மின்னஞ்சல் நினைவூட்டல்கள்",
  "Background browser alerts": "பின்னணி உலாவி எச்சரிக்கைகள்",
  "Save notification settings": "அறிவிப்பு அமைப்புகளை சேமி",
  "Sync now": "இப்போது ஒத்திசை",
  "Syncing...": "ஒத்திசைக்கிறது...",
  "Mark all read": "அனைத்தையும் படித்ததாக குறி",
  "Recent signals": "சமீபத்திய சிக்னல்கள்",
  "Latest pressure from the system.": "அமைப்பிலிருந்து சமீபத்திய அழுத்தம்.",
  "Unread": "படிக்காதது",
  "Read": "படிக்கப்பட்டது",
  "Build a learning engine around what you know and what you still need.": "நீங்கள் அறிந்ததும் இன்னும் கற்றுக்கொள்ள வேண்டியதும் அடிப்படையாக கற்றல் இயந்திரத்தை உருவாக்குங்கள்.",
  "Input system": "உள்ளீட்டு அமைப்பு",
  "Editable, tag-based planning": "திருத்தக்கூடிய, குறிச்சொல் அடிப்படையிலான திட்டமிடல்",
  "Generate Plan": "திட்டத்தை உருவாக்கு",
  "Edit Plan": "திட்டத்தைத் திருத்து",
  "Regenerate Plan": "திட்டத்தை மீண்டும் உருவாக்கு",
  "Update Plan": "திட்டத்தை புதுப்பி",
  "What do you know?": "நீங்கள் என்ன அறிவீர்கள்?",
  "What do you want to learn?": "நீங்கள் என்ன கற்றுக்கொள்ள விரும்புகிறீர்கள்?",
  "Search or add known topics": "அறிந்த தலைப்புகளை தேடு அல்லது சேர்",
  "Search or add target topics": "இலக்கு தலைப்புகளை தேடு அல்லது சேர்",
  "Time per day": "ஒரு நாளுக்கு நேரம்",
  "Plan duration": "திட்ட காலம்",
  "Plan language": "திட்ட மொழி",
  "Choose a role": "ஒரு பங்கைத் தேர்வு செய்",
  "Choose a language": "ஒரு மொழியைத் தேர்வு செய்",
  "Version history": "பதிப்பு வரலாறு",
  "Clear": "அழி",
  "Current plan": "தற்போதைய திட்டம்",
  "Mentor line": "வழிகாட்டி வரி",
  "Roadmap": "சாலை வரைபடம்",
  "Study stack": "படிப்பு தொகுப்பு",
  "Flashcards": "ஃபிளாஷ்கார்டுகள்",
  "Assessments stay role-aware.": "மதிப்பீடுகள் பங்கு சார்ந்தவையாக இருக்கும்.",
  "Assessment Builder": "மதிப்பீட்டு உருவாக்கி",
  "MCQ sprint": "MCQ வேகப் பயிற்சி",
  "Fill in the blanks": "காலியிடங்களை நிரப்புக",
  "Short programming": "குறுகிய நிரலாக்கம்",
  "Daily focus": "தினசரி கவனம்",
  "Weekly sweep": "வாராந்திர மதிப்பீடு",
  "Assessment duration": "மதிப்பீட்டு காலம்",
  "Start assessment": "மதிப்பீட்டை தொடங்கு",
  "Submit assessment": "மதிப்பீட்டை சமர்ப்பி",
  "Regenerate": "மீண்டும் உருவாக்கு",
  "Current assessment": "தற்போதைய மதிப்பீடு",
  "Recent assessments": "சமீபத்திய மதிப்பீடுகள்",
  "No assessment started yet.": "இன்னும் மதிப்பீடு தொடங்கவில்லை.",
  "Mission Control": "பணி கட்டுப்பாடு",
  "Details": "விவரங்கள்",
  "Hide details": "விவரங்களை மறை",
  "Open reference": "குறிப்பு இணைப்பைத் திற",
  "Resume intelligence": "ரெச்யூமே பகுப்பாய்வு",
  "Job-specific ATS check": "வேலை விவரத்திற்கான ATS சோதனை",
  "Paste job description": "வேலை விவரத்தை ஒட்டு",
  "Score against JD": "JD அடிப்படையில் மதிப்பெண் கணக்கு",
  "Placement countdown": "பிளேஸ்மெண்ட் கவுண்ட்டவுன்",
  "Days Remaining": "மீதமுள்ள நாட்கள்",
  "Target placement date": "இலக்கு பிளேஸ்மெண்ட் தேதி",
  "Placement date is not set": "பிளேஸ்மெண்ட் தேதி அமைக்கப்படவில்லை",
  "Focus Area": "கவனப் பகுதி",
  "CommandLine": "கட்டளை வரி",
  "Mentor Signal": "வழிகாட்டி சிக்னல்",
  "Power Pocket": "பவர் பாக்கெட்",
  "Deep work sprint": "ஆழ்ந்த வேலைப் பயிற்சி",
  "Quick Mission": "விரைவுப் பணி",
  "Start Power Pocket": "பவர் பாக்கெட் தொடங்கு",
  "End Session": "அமர்வை முடி",
  "Focus Mode": "கவன நிலை",
  "Active sprint": "செயலில் உள்ள பயிற்சி",
  "Suggested Task": "பரிந்துரைக்கப்பட்ட பணி",
  "No active session": "செயலில் அமர்வு இல்லை",
  "Quick task": "விரைவுப் பணி",
  "Build a quick task": "விரைவுப் பணியை உருவாக்கு",
  "Generate quick task": "விரைவுப் பணியை உருவாக்கு",
  "Minutes": "நிமிடங்கள்",
  "minutes": "நிமிடங்கள்",
  "Coach Profile": "பயிற்சியாளர் விவரம்",
  "Performance Diagnostics": "செயல்திறன் ஆய்வுகள்",
  "Solved Problems": "தீர்க்கப்பட்ட சிக்கல்கள்",
  "Average Time": "சராசரி நேரம்",
  "Streak": "தொடர்ச்சி",
  "Mistake Count": "தவறுகளின் எண்ணிக்கை",
  "Failed Attempts": "தோல்வியுற்ற முயற்சிகள்",
  "Tracked Days": "கண்காணிக்கப்பட்ட நாட்கள்",
  "Target Role": "இலக்கு பங்கு",
  "Readiness Score": "தயார்நிலை மதிப்பெண்",
  "Consistency Score": "தொடர்ச்சித்தன்மை மதிப்பெண்",
  "Curriculum engine": "பாடத்திட்ட இயந்திரம்",
  "Target company": "இலக்கு நிறுவனம்",
  "Company track": "நிறுவனப் பாதை",
  "Custom company": "தனிப்பயன் நிறுவனம்",
  "Company name": "நிறுவனத்தின் பெயர்",
  "Known topics": "அறிந்த தலைப்புகள்",
  "Target topics": "இலக்கு தலைப்புகள்",
  "Manage versions": "பதிப்புகளை நிர்வகி",
  "Week-wise plan": "வாராந்திர திட்டம்",
  "Daily tasks": "தினசரி பணிகள்",
  "Structured execution": "கட்டமைக்கப்பட்ட செயல்பாடு",
  "Resources": "வளங்கள்",
  "Recall drills": "நினைவுகூறும் பயிற்சிகள்",
  "Practice in Coding Lab": "கோடிங் ஆய்வகத்தில் பயிற்சி செய்",
  "Lab": "ஆய்வகம்",
  "Expand": "விரிவாக்கு",
  "hours / week": "மணி / வாரம்",
  "hours / day": "மணி / நாள்",
  "hours": "மணிநேரம்",
  "mins": "நிமிடங்கள்",
  "Rename version": "பதிப்பை மறுபெயரிடு",
  "Activate version": "பதிப்பை செயல்படுத்து",
  "Delete version": "பதிப்பை நீக்கு",
  "Diagnostic checks": "கண்டறியும் சோதனைகள்",
  "Question": "கேள்வி",
  "Previous": "முந்தைய",
  "Next": "அடுத்தது",
  "Finish": "முடி",
  "Review": "மதிப்பாய்வு",
  "Your score": "உங்கள் மதிப்பெண்",
  "Accuracy": "துல்லியம்",
  "Correct": "சரி",
  "Incorrect": "தவறு",
  "Feedback": "கருத்து",
  "Recommendation": "பரிந்துரை",
  "Topic breakdown": "தலைப்பு பகுப்பாய்வு",
  "Coding Lab": "கோடிங் ஆய்வகம்",
  "Interactive compiler & test runner": "ஊடாடும் தொகுப்பி மற்றும் சோதனை இயக்கி",
  "Problem statement": "சிக்கல் அறிக்கை",
  "Description": "விளக்கம்",
  "Input": "உள்ளீடு",
  "Output": "வெளியீடு",
  "Constraints": "வரம்புகள்",
  "Examples": "எடுத்துக்காட்டுகள்",
  "Run Code": "குறியீட்டை இயக்கு",
  "Submit Code": "குறியீட்டை சமர்ப்பி",
  "Submissions": "சமர்ப்பிப்புகள்",
  "Language": "மொழி",
  "Test Cases": "சோதனை வழக்குகள்",
  "Expected Output": "எதிர்பார்க்கப்படும் வெளியீடு",
  "Your Output": "உங்கள் வெளியீடு",
  "Console Output": "கன்சோல் வெளியீடு",
  "Passed": "வெற்றி",
  "Failed": "தோல்வி",
  "Execution Time": "செயல்படுத்தும் நேரம்",
  "Memory": "நினைவகம்",
  "Resume ATS Scanner": "ரெச்யூமே ATS ஸ்கேனர்",
  "ATS Match Score": "ATS பொருத்த மதிப்பெண்",
  "Matched keywords": "பொருந்திய முக்கிய வார்த்தைகள்",
  "Missing keywords": "விடுபட்ட முக்கிய வார்த்தைகள்",
  "Formatting score": "வடிவமைப்பு மதிப்பெண்",
  "Section coverage": "பிரிவு பாதுகாப்பு",
  "Tailored suggestions": "தனிப்பயனாக்கப்பட்ட பரிந்துரைகள்",
  "Upload resume": "ரெச்யூமே பதிவேற்று",
  "Drop your resume here": "உங்கள் ரெச்யூமேயை இங்கே இழுத்து விடுங்கள்",
  "Analyze resume": "ரெச்யூமே பகுப்பாய்வு செய்",
  "Clear history": "வரலாற்றை அழி",
  "Focus Missions": "கவனப் பணிகள்",
  "Filter by date": "தேதி வாரியாக வடிகட்டு",
  "Filter by status": "நிலை வாரியாக வடிகட்டு",
  "Filter by category": "வகை வாரியாக வடிகட்டு",
  "All tasks": "அனைத்து பணிகள்",
  "New task": "புதிய பணி",
  "Task title": "பணி தலைப்பு",
  "Category": "வகை",
  "Difficulty": "சிரமம்",
  "Estimated minutes": "மதிப்பிடப்பட்ட நிமிடங்கள்",
  "Priority": "முன்னுரிமை",
  "Low": "குறைவு",
  "Medium": "நடுத்தரம்",
  "High": "அதிகம்",
  "Pending": "நிலுவையில்",
  "In progress": "செயலில்",
  "Completed": "முடிந்தது",
  "Skipped": "தவிர்க்கப்பட்டது",
  "Overdue": "தாமதமானது",
  "Mark completed": "முடிந்ததாகக் குறி",
  "Mark in progress": "செயலில் உள்ளதாகக் குறி",
  "Skip task": "பணியைத் தவிர்",
  "Delete task": "பணியை நீக்கு",
  "Clear completed": "முடிந்தவற்றை அழி",
  "Personal Profile": "தனிப்பட்ட சுயவிவரம்",
  "Email": "மின்னஞ்சல்",
  "Strict notifications": "கடுமையான அறிவிப்புகள்",
  "Billing": "பில்லிங்",
  "PlacePrep access": "PlacePrep அணுகல்",
  "Current tier": "தற்போதைய அடுக்கு",
  "Manage billing": "பில்லிங்கை நிர்வகி",
  "Upgrade to Pro": "ப்ரோவுக்கு மேம்படுத்து",
  "Android App": "ஆண்ட்ராய்டு செயலி",
  "Download APK": "APK பதிவிறக்கு",
  "Are you sure?": "நிச்சயமாகவா?",
  "This action cannot be undone.": "இந்த செயலை திரும்பப் பெற முடியாது.",
  "Confirm": "உறுதிப்படுத்து",
  "Close": "மூடு",
  "Delete": "நீக்கு",
  "Cancel": "ரத்து செய்",
  "Save changes": "மாற்றங்களைச் சேமி",
  "Saved": "சேமிக்கப்பட்டது",
  "Updated": "புதுப்பிக்கப்பட்டது",
  "Deleted": "நீக்கப்பட்டது",
  "Try again": "மீண்டும் முயற்சி செய்",
  "Admin Console": "நிர்வாகக் கட்டுப்பாடு",
  "Student Oversight": "மாணவர் மேற்பார்வை",
  "Practice Capsules": "பயிற்சி பெட்டகங்கள்",
  "Upload proof": "ஆதாரம் பதிவேற்று",
  "Recent proofs": "சமீபத்திய ஆதாரங்கள்",
  "Clear all": "அனைத்தையும் அழி",
  "Select all": "அனைத்தையும் தேர்ந்தெடு",
  "Action": "செயல்",
  "Status": "நிலை",
};

const HINDI_TRANSLATIONS: TranslationTable = {
  "Loading workspace": "वर्कस्पेस लोड हो रहा है",
  "Restoring your PlacePrep session.": "आपका PlacePrep सत्र बहाल हो रहा है.",
  "Navigate": "नेविगेट",
  "Signals": "सिग्नल",
  "AI status": "AI स्थिति",
  "Live": "लाइव",
  "Fallback": "फॉलबैक",
  "checking": "जांच रहा है",
  "offline": "ऑफलाइन",
  "Command Chamber": "कमांड चेंबर",
  "Prep Architect": "प्रेप आर्किटेक्ट",
  "Assessments": "मूल्यांकन",
  "Tasks": "कार्य",
  "Progress": "प्रगति",
  "Nocturne Mentor": "नॉक्टर्न मेंटर",
  "Settings": "सेटिंग्स",
  "Profile": "प्रोफ़ाइल",
  "Clock. Focus. Execute.": "समय. ध्यान. निष्पादन.",
  "Map. Practice. Recall.": "मैप. अभ्यास. याद.",
  "Queue. Strike. Clear.": "कतार. वार. साफ़.",
  "Probe. Measure. Adapt.": "जांच. माप. सुधार.",
  "Signal. Drift. Recover.": "सिग्नल. भटकाव. रिकवरी.",
  "Presence. Craft. Proof.": "उपस्थिति. निर्माण. प्रमाण.",
  "Tune. Save. Return.": "ट्यून. सेव. वापसी.",
  "Ask. Refine. Advance.": "पूछें. सुधारें. आगे बढ़ें.",
  "How it works": "यह कैसे काम करता है",
  "AI live": "AI लाइव",
  "Checking": "जांच रहा है",
  "Demo mode": "डेमो मोड",
  "Open navigation": "नेविगेशन खोलें",
  "Open profile menu": "प्रोफ़ाइल मेनू खोलें",
  "Logout": "लॉगआउट",
  "Observer access": "ऑब्ज़र्वर एक्सेस",
  "Architect sync": "आर्किटेक्ट सिंक",
  "Refresh": "रिफ्रेश",
  "Open Prep Architect": "प्रेप आर्किटेक्ट खोलें",
  "Readiness": "तैयारी",
  "Consistency": "निरंतरता",
  "Execution": "निष्पादन",
  "Idle": "निष्क्रिय",
  "Active": "सक्रिय",
  "Today's tasks": "आज के कार्य",
  "No tasks scheduled": "आज कोई कार्य तय नहीं",
  "Generate a coach plan to build today's work around your actual weak areas.": "अपने वास्तविक कमजोर क्षेत्रों के आधार पर आज का काम बनाने के लिए कोच प्लान जनरेट करें.",
  "Coach Console": "कोच कंसोल",
  "Personal planning, rescue, and daily review.": "व्यक्तिगत योजना, सहायता, और दैनिक समीक्षा.",
  "Generate Today's Plan": "आज का प्लान जनरेट करें",
  "Generate and deploy plan": "प्लान जनरेट और लागू करें",
  "Generating plan...": "प्लान बन रहा है...",
  "I'm Stuck": "मैं अटक गया हूं",
  "Problem name or topic": "समस्या का नाम या टॉपिक",
  "What have you tried? Where exactly are you blocked?": "आपने क्या कोशिश की? आप कहां अटके हैं?",
  "Coach me through it": "मुझे इसमें गाइड करें",
  "Evaluate Today": "आज का मूल्यांकन",
  "Run daily evaluation": "दैनिक मूल्यांकन चलाएं",
  "Productivity score": "उत्पादकता स्कोर",
  "Weak areas": "कमजोर क्षेत्र",
  "Fix tomorrow": "कल सुधारें",
  "Hint": "संकेत",
  "Progressive Hint": "प्रगतिशील संकेत",
  "Approach": "तरीका",
  "Approach Steps": "दृष्टिकोण के चरण",
  "Practice Next": "अगला अभ्यास",
  "Recommended Practice": "अनुशंसित अभ्यास",
  "Search Keywords": "खोज कीवर्ड",
  "Rescue": "बचाव",
  "Plan": "योजना",
  "Review": "समीक्षा",
  "Analyzing problem...": "समस्या का विश्लेषण हो रहा है...",
  "Next Best Action": "अगला सर्वश्रेष्ठ कदम",
  "Focus Sprint": "फोकस स्प्रिंट",
  "Start 25m Focus Sprint": "25 मिनट का फोकस स्प्रिंट शुरू करें",
  "Execution Summary": "निष्पादन सारांश",
  "No tasks scheduled for today": "आज के लिए कोई कार्य निर्धारित नहीं है",
  "Hold the line until placement day.": "प्लेसमेंट के दिन तक अपनी स्थिति बनाए रखें.",
  "Control identity, links, and system behavior.": "पहचान, लिंक, और सिस्टम व्यवहार नियंत्रित करें.",
  "Account": "खाता",
  "Username and profile": "यूज़रनेम और प्रोफ़ाइल",
  "Display name": "डिस्प्ले नाम",
  "Username": "यूज़रनेम",
  "Target role": "लक्ष्य भूमिका",
  "Placement date": "प्लेसमेंट तारीख",
  "Preferred language": "पसंदीदा भाषा",
  "Save account settings": "खाता सेटिंग्स सेव करें",
  "Saving...": "सेव हो रहा है...",
  "Notifications": "सूचनाएं",
  "Strict signals. No fluff.": "सख्त सिग्नल. कोई फालतू नहीं.",
  "Daily reminders, pending task pressure, streak warnings, deadline urgency, and sharp motivation.": "दैनिक रिमाइंडर, लंबित कार्य दबाव, स्ट्रीक चेतावनी, डेडलाइन अर्जेंसी, और साफ़ मोटिवेशन.",
  "Browser permission": "ब्राउज़र अनुमति",
  "Strict notifications": "सख्त सूचनाएं",
  "Master switch for all mentor reminders.": "सभी मेंटर रिमाइंडर के लिए मुख्य स्विच.",
  "Email prompts": "ईमेल संकेत",
  "Background browser alerts": "बैकग्राउंड ब्राउज़र अलर्ट",
  "Save notification settings": "सूचना सेटिंग्स सेव करें",
  "Sync now": "अभी सिंक करें",
  "Syncing...": "सिंक हो रहा है...",
  "Mark all read": "सबको पढ़ा हुआ करें",
  "Recent signals": "हाल के सिग्नल",
  "Latest pressure from the system.": "सिस्टम से नवीनतम दबाव.",
  "Unread": "अपठित",
  "Read": "पढ़ा हुआ",
  "Build a learning engine around what you know and what you still need.": "जो आप जानते हैं और जो अभी सीखना है, उसके आधार पर लर्निंग इंजन बनाएं.",
  "Input system": "इनपुट सिस्टम",
  "Editable, tag-based planning": "संपादन योग्य, टैग आधारित योजना",
  "Generate Plan": "प्लान जनरेट करें",
  "Edit Plan": "प्लान संपादित करें",
  "Regenerate Plan": "प्लान दोबारा बनाएं",
  "Update Plan": "प्लान अपडेट करें",
  "What do you know?": "आप क्या जानते हैं?",
  "What do you want to learn?": "आप क्या सीखना चाहते हैं?",
  "Search or add known topics": "ज्ञात टॉपिक खोजें या जोड़ें",
  "Search or add target topics": "लक्ष्य टॉपिक खोजें या जोड़ें",
  "Time per day": "हर दिन समय",
  "Plan duration": "प्लान अवधि",
  "Plan language": "प्लान भाषा",
  "Choose a role": "भूमिका चुनें",
  "Choose a language": "भाषा चुनें",
  "Version history": "वर्ज़न इतिहास",
  "Clear": "साफ़ करें",
  "Current plan": "वर्तमान प्लान",
  "Mentor line": "मेंटर लाइन",
  "Roadmap": "रोडमैप",
  "Study stack": "स्टडी स्टैक",
  "Flashcards": "फ्लैशकार्ड",
  "Assessments stay role-aware.": "मूल्यांकन भूमिका के अनुसार रहेंगे.",
  "Assessment Builder": "मूल्यांकन बिल्डर",
  "MCQ sprint": "MCQ स्प्रिंट",
  "Fill in the blanks": "रिक्त स्थान भरें",
  "Short programming": "छोटी प्रोग्रामिंग",
  "Daily focus": "दैनिक फोकस",
  "Weekly sweep": "साप्ताहिक समीक्षा",
  "Assessment duration": "मूल्यांकन अवधि",
  "Start assessment": "मूल्यांकन शुरू करें",
  "Submit assessment": "मूल्यांकन जमा करें",
  "Regenerate": "दोबारा बनाएं",
  "Current assessment": "वर्तमान मूल्यांकन",
  "Recent assessments": "हाल के मूल्यांकन",
  "No assessment started yet.": "अभी कोई मूल्यांकन शुरू नहीं हुआ.",
  "Mission Control": "मिशन कंट्रोल",
  "Details": "विवरण",
  "Hide details": "विवरण छिपाएं",
  "Open reference": "संदर्भ खोलें",
  "Resume intelligence": "रिज़्यूमे इंटेलिजेंस",
  "Job-specific ATS check": "जॉब-विशिष्ट ATS जांच",
  "Paste job description": "जॉब विवरण पेस्ट करें",
  "Score against JD": "JD के अनुसार स्कोर करें",
  "Placement countdown": "प्लेसमेंट उलटी गिनती",
  "Days Remaining": "शेष दिन",
  "Target placement date": "लक्ष्य प्लेसमेंट तारीख",
  "Placement date is not set": "प्लेसमेंट तारीख सेट नहीं है",
  "Focus Area": "फोकस क्षेत्र",
  "CommandLine": "कमांड लाइन",
  "Mentor Signal": "मेंटर सिग्नल",
  "Power Pocket": "पावर पॉकेट",
  "Deep work sprint": "गहन कार्य स्प्रिंट",
  "Quick Mission": "त्वरित मिशन",
  "Start Power Pocket": "पावर पॉकेट शुरू करें",
  "End Session": "सत्र समाप्त करें",
  "Focus Mode": "फोकस मोड",
  "Active sprint": "सक्रिय स्प्रिंट",
  "Suggested Task": "सुझाया गया कार्य",
  "No active session": "कोई सक्रिय सत्र नहीं",
  "Quick task": "त्वरित कार्य",
  "Build a quick task": "त्वरित कार्य बनाएं",
  "Generate quick task": "त्वरित कार्य जनरेट करें",
  "Minutes": "मिनट",
  "minutes": "मिनट",
  "Coach Profile": "कोच प्रोफ़ाइल",
  "Performance Diagnostics": "प्रदर्शन निदान",
  "Solved Problems": "हल की गई समस्याएं",
  "Average Time": "औसत समय",
  "Streak": "स्ट्रीक",
  "Mistake Count": "गलतियों की संख्या",
  "Failed Attempts": "विफल प्रयास",
  "Tracked Days": "ट्रैक किए गए दिन",
  "Target Role": "लक्ष्य भूमिका",
  "Readiness Score": "तैयारी स्कोर",
  "Consistency Score": "निरंतरता स्कोर",
  "Curriculum engine": "पाठ्यक्रम इंजन",
  "Target company": "लक्ष्य कंपनी",
  "Company track": "कंपनी ट्रैक",
  "Custom company": "कस्टम कंपनी",
  "Company name": "कंपनी का नाम",
  "Known topics": "ज्ञात टॉपिक",
  "Target topics": "लक्ष्य टॉपिक",
  "Manage versions": "वर्ज़न प्रबंधित करें",
  "Week-wise plan": "सप्ताह-वार योजना",
  "Daily tasks": "दैनिक कार्य",
  "Structured execution": "संरचित निष्पादन",
  "Resources": "संसाधन",
  "Recall drills": "रिकॉल अभ्यास",
  "Practice in Coding Lab": "कोडिंग लैब में अभ्यास करें",
  "Lab": "लैब",
  "Expand": "विस्तार करें",
  "hours / week": "घंटे / सप्ताह",
  "hours / day": "घंटे / दिन",
  "hours": "घंटे",
  "mins": "मिनट",
  "Rename version": "वर्ज़न का नाम बदलें",
  "Activate version": "वर्ज़न सक्रिय करें",
  "Delete version": "वर्ज़न हटाएं",
  "Diagnostic checks": "डायग्नोस्टिक टेस्ट",
  "Question": "प्रश्न",
  "Previous": "पिछला",
  "Next": "अगला",
  "Finish": "समाप्त",
  "Review": "समीक्षा",
  "Your score": "आपका स्कोर",
  "Accuracy": "सटीकता",
  "Correct": "सही",
  "Incorrect": "गलत",
  "Feedback": "प्रतिक्रिया",
  "Recommendation": "सिफारिश",
  "Topic breakdown": "टॉपिक विश्लेषण",
  "Coding Lab": "कोडिंग लैब",
  "Interactive compiler & test runner": "इंटरएक्टिव कंपाइलर और टेस्ट रनर",
  "Problem statement": "समस्या विवरण",
  "Description": "विवरण",
  "Input": "इनपुट",
  "Output": "आउटपुट",
  "Constraints": "सीमाएं",
  "Examples": "उदाहरण",
  "Run Code": "कोड चलाएं",
  "Submit Code": "कोड जमा करें",
  "Submissions": "सबमिशन",
  "Language": "भाषा",
  "Test Cases": "टेस्ट केस",
  "Expected Output": "अपेक्षित आउटपुट",
  "Your Output": "आपका आउटपुट",
  "Console Output": "कंसोल आउटपुट",
  "Passed": "सफल",
  "Failed": "विफल",
  "Execution Time": "निष्पादन समय",
  "Memory": "मेमोरी",
  "Resume ATS Scanner": "रिज़्यूमे ATS स्कैनर",
  "ATS Match Score": "ATS मैच स्कोर",
  "Matched keywords": "मेल खाने वाले कीवर्ड",
  "Missing keywords": "लापता कीवर्ड",
  "Formatting score": "फॉर्मेटिंग स्कोर",
  "Section coverage": "अनुभाग कवरेज",
  "Tailored suggestions": "अनुकूलित सुझाव",
  "Upload resume": "रिज़्यूमे अपलोड करें",
  "Drop your resume here": "अपना रिज़्यूमे यहाँ डालें",
  "Analyze resume": "रिज़्यूमे का विश्लेषण करें",
  "Clear history": "इतिहास साफ़ करें",
  "Focus Missions": "फोकस मिशन",
  "Filter by date": "तारीख के अनुसार फ़िल्टर करें",
  "Filter by status": "स्थिति के अनुसार फ़िल्टर करें",
  "Filter by category": "श्रेणी के अनुसार फ़िल्टर करें",
  "All tasks": "सभी कार्य",
  "New task": "नया कार्य",
  "Task title": "कार्य शीर्षक",
  "Category": "श्रेणी",
  "Difficulty": "कठिनाई",
  "Estimated minutes": "अनुमानित मिनट",
  "Priority": "प्राथमिकता",
  "Low": "कम",
  "Medium": "मध्यम",
  "High": "उच्च",
  "Pending": "लंबित",
  "In progress": "प्रगति में",
  "Completed": "पूर्ण",
  "Skipped": "छोड़ दिया गया",
  "Overdue": "विलंबित",
  "Mark completed": "पूर्ण के रूप में चिह्नित करें",
  "Mark in progress": "प्रगति में चिह्नित करें",
  "Skip task": "कार्य छोड़ें",
  "Delete task": "कार्य हटाएं",
  "Clear completed": "पूर्ण कार्य साफ़ करें",
  "Personal Profile": "व्यक्तिगत प्रोफ़ाइल",
  "Email": "ईमेल",
  "Strict notifications": "सख्त सूचनाएं",
  "Billing": "बिलिंग",
  "PlacePrep access": "PlacePrep एक्सेस",
  "Current tier": "वर्तमान स्तर",
  "Manage billing": "बिलिंग प्रबंधित करें",
  "Upgrade to Pro": "प्रो में अपग्रेड करें",
  "Android App": "एंड्रॉइड ऐप",
  "Download APK": "APK डाउनलोड करें",
  "Are you sure?": "क्या आप सुनिश्चित हैं?",
  "This action cannot be undone.": "यह कार्रवाई पूर्ववत नहीं की जा सकती.",
  "Confirm": "पुष्टि करें",
  "Close": "बंद करें",
  "Delete": "हटाएं",
  "Cancel": "रद्द करें",
  "Save changes": "परिवर्तन सहेजें",
  "Saved": "सहेजा गया",
  "Updated": "अपडेट किया गया",
  "Deleted": "हटाया गया",
  "Try again": "पुनः प्रयास करें",
  "Admin Console": "व्यवस्थापक कंसोल",
  "Student Oversight": "छात्र निगरानी",
  "Practice Capsules": "अभ्यास कैप्सूल",
  "Upload proof": "प्रमाण अपलोड करें",
  "Recent proofs": "हाल के प्रमाण",
  "Clear all": "सब साफ़ करें",
  "Select all": "सभी चुनें",
  "Action": "कार्रवाई",
  "Status": "स्थिति",
};

const FRAGMENT_TRANSLATIONS: Record<Exclude<UiLanguage, "english">, TranslationTable> = {
  tamil: {
    "Some live dashboard data is temporarily unavailable.": "சில நேரலை டாஷ்போர்டு தரவு தற்காலிகமாக கிடைக்கவில்லை.",
    "The command center is still visible with safe defaults.": "கட்டளை மையம் பாதுகாப்பான இயல்புநிலை மதிப்புகளுடன் காணப்படுகிறது.",
    "Retry to pull the latest state back in.": "சமீபத்திய நிலையை மீண்டும் பெற முயற்சிக்கவும்.",
    "Some non-critical live signals are temporarily unavailable.": "சில முக்கியமற்ற நேரலை சிக்னல்கள் தற்காலிகமாக கிடைக்கவில்லை.",
    "Your core dashboard is still usable, and refresh will retry the missing syncs.": "உங்கள் முக்கிய டாஷ்போர்டு பயன்படுத்தக்கூடியது, புதுப்பித்தல் விடுபட்ட ஒத்திசைவுகளை மீண்டும் முயற்சிக்கும்.",
    "Completed tasks across the last seven days.": "கடந்த ஏழு நாட்களில் முடிக்கப்பட்ட பணிகள்.",
    "Strength shifts based on completion quality and consistency.": "செயல்பாட்டின் தரம் மற்றும் தொடர்ச்சியைப் பொறுத்து பலம் மாறும்.",
    "Your Prep Architect plan is active": "உங்கள் தயாரிப்பு வடிவமைப்பு திட்டம் செயலில் உள்ளது",
    "No architect plan yet. Build one to turn weak areas into a structured roadmap.": "இன்னும் தயாரிப்பு திட்டம் இல்லை. பலவீனங்களை ஒரு கட்டமைக்கப்பட்ட திட்டமாக மாற்ற ஒன்றை உருவாக்குங்கள்.",
    "No roadmap weeks are available yet. Regenerate the plan to rebuild the weekly structure.": "இன்னும் வாராந்திர திட்டங்கள் கிடைக்கவில்லை. வாராந்திர கட்டமைப்பை மீண்டும் உருவாக்க திட்டத்தை மீண்டும் உருவாக்கவும்.",
    "No daily task blocks are available yet. Update the plan to regenerate structured execution.": "இன்னும் தினசரி பணி தொகுதிகள் கிடைக்கவில்லை. கட்டமைக்கப்பட்ட செயல்பாட்டை உருவாக்க திட்டத்தை புதுப்பிக்கவும்.",
    "Resource links are missing for this version. Regenerate the plan to rebuild the study stack.": "இந்த பதிப்பிற்கான வள இணைப்புகள் விடுபட்டுள்ளன. படிப்பு தொகுப்பை மீண்டும் உருவாக்க திட்டத்தை மீண்டும் உருவாக்கவும்.",
    "Flashcards are unavailable for this version. Update the plan to rebuild recall drills.": "இந்த பதிப்பிற்கான ஃபிளாஷ்கார்டுகள் கிடைக்கவில்லை. நினைவுகூறும் பயிற்சிகளை மீண்டும் உருவாக்க திட்டத்தை புதுப்பிக்கவும்.",
    "Switches the workspace UI instantly. Saving account settings keeps the choice synced to your account.": "பணியிட இடைமுகத்தை உடனடியாக மாற்றுகிறது. கணக்கு அமைப்புகளை சேமிப்பது உங்கள் கணக்குடன் ஒத்திசைவாக வைத்திருக்கும்.",
    "Master switch for all mentor reminders.": "அனைத்து வழிகாட்டி நினைவூட்டல்களுக்கான முதன்மை சுவிட்ச்.",
    "Daily reminders, pending task pressure, streak warnings, deadline urgency, and sharp motivation.": "தினசரி நினைவூட்டல்கள், நிலுவைப் பணி அழுத்தம், தொடர்ச்சி எச்சரிக்கை, காலக்கெடு அவசரம், மற்றும் தெளிவான ஊக்கம்.",
    "is active for": "செயலில் உள்ளது:",
    " is active": " செயலில் உள்ளது",
    " is synced into the system.": " அமைப்பில் ஒத்திசைக்கப்பட்டுள்ளது.",
    "No active architect plan yet.": "இன்னும் செயலில் உள்ள வடிவமைப்பு திட்டம் இல்லை.",
    "Build one": "ஒன்றை உருவாக்குங்கள்",
    "hours / week": "மணி / வாரம்",
    "hours / day": "மணி / நாள்",
    "hours": "மணிநேரம்",
    "month": "மாதம்",
    "months": "மாதங்கள்",
    "hrs": "மணி",
    "hr": "மணி",
    "Retry": "மீண்டும் முயற்சி",
    "Cancel": "ரத்து செய்",
    "Delete selected": "தேர்ந்தெடுத்ததை நீக்கு",
    "Use version": "இந்த பதிப்பை பயன்படுத்து",
  },
  hindi: {
    "Some live dashboard data is temporarily unavailable.": "कुछ लाइव डैशबोर्ड डेटा अस्थायी रूप से अनुपलब्ध है.",
    "The command center is still visible with safe defaults.": "कमांड सेंटर सुरक्षित डिफ़ॉल्ट मानों के साथ दिखाई दे रहा है.",
    "Retry to pull the latest state back in.": "नवीनतम स्थिति वापस लाने के लिए पुनः प्रयास करें.",
    "Some non-critical live signals are temporarily unavailable.": "कुछ गैर-महत्वपूर्ण लाइव सिग्नल अस्थायी रूप से अनुपलब्ध हैं.",
    "Your core dashboard is still usable, and refresh will retry the missing syncs.": "आपका मुख्य डैशबोर्ड अभी भी उपयोग करने योग्य है, और रिफ्रेश करने पर छूटे हुए सिंक का पुनः प्रयास होगा.",
    "Completed tasks across the last seven days.": "पिछले सात दिनों में पूरे किए गए कार्य.",
    "Strength shifts based on completion quality and consistency.": "कार्य की गुणवत्ता और निरंतरता के आधार पर ताकत बदलती है.",
    "Your Prep Architect plan is active": "आपका प्रेप आर्किटेक्ट प्लान सक्रिय है",
    "No architect plan yet. Build one to turn weak areas into a structured roadmap.": "अभी कोई आर्किटेक्ट प्लान नहीं है. कमजोर क्षेत्रों को एक संरचित रोडमैप में बदलने के लिए एक प्लान बनाएं.",
    "No roadmap weeks are available yet. Regenerate the plan to rebuild the weekly structure.": "अभी कोई रोडमैप सप्ताह उपलब्ध नहीं है. साप्ताहिक संरचना दोबारा बनाने के लिए प्लान को पुनः जनरेट करें.",
    "No daily task blocks are available yet. Update the plan to regenerate structured execution.": "अभी कोई दैनिक कार्य ब्लॉक उपलब्ध नहीं है. संरचित निष्पादन बनाने के लिए प्लान को अपडेट करें.",
    "Resource links are missing for this version. Regenerate the plan to rebuild the study stack.": "इस वर्ज़न के लिए संसाधन लिंक गायब हैं. अध्ययन स्टैक बनाने के लिए प्लान को पुनः जनरेट करें.",
    "Flashcards are unavailable for this version. Update the plan to rebuild recall drills.": "इस वर्ज़न के लिए फ्लैशकार्ड उपलब्ध नहीं हैं. रिकॉल अभ्यास बनाने के लिए प्लान को अपडेट करें.",
    "Switches the workspace UI instantly. Saving account settings keeps the choice synced to your account.": "कार्यक्षेत्र UI को तुरंत बदलता है। खाता सेटिंग्स सहेजने से यह आपकी पसंद के साथ समन्वयित रहता है।",
    "Master switch for all mentor reminders.": "सभी मेंटर रिमाइंडर के लिए मुख्य स्विच.",
    "Daily reminders, pending task pressure, streak warnings, deadline urgency, and sharp motivation.": "दैनिक रिमाइंडर, लंबित कार्य दबाव, स्ट्रीक चेतावनी, डेडलाइन अर्जेंसी, और स्पष्ट मोटिवेशन.",
    "is active for": "सक्रिय है इसके लिए:",
    " is active": " सक्रिय है",
    " is synced into the system.": " सिस्टम में सिंक है.",
    "No active architect plan yet.": "अभी कोई सक्रिय आर्किटेक्ट प्लान नहीं है.",
    "Build one": "एक बनाएं",
    "hours / week": "घंटे / सप्ताह",
    "hours / day": "घंटे / दिन",
    "hours": "घंटे",
    "month": "माह",
    "months": "माह",
    "hrs": "घंटे",
    "hr": "घंटा",
    "Retry": "फिर कोशिश करें",
    "Cancel": "रद्द करें",
    "Delete selected": "चयनित हटाएं",
    "Use version": "इस वर्ज़न का उपयोग करें",
  },
};

const TRANSLATIONS: Record<Exclude<UiLanguage, "english">, TranslationTable> = {
  tamil: TAMIL_TRANSLATIONS,
  hindi: HINDI_TRANSLATIONS,
};

export function normalizeUiLanguage(value: unknown): UiLanguage {
  const normalized = String(value || "").trim().toLowerCase();
  return normalized === "tamil" || normalized === "hindi" ? normalized : "english";
}

export function getUiLanguageOption(language: UiLanguage) {
  return UI_LANGUAGE_OPTIONS.find((option) => option.value === language) || UI_LANGUAGE_OPTIONS[0];
}

function preserveWhitespace(source: string, translated: string) {
  const leading = source.match(/^\s*/)?.[0] || "";
  const trailing = source.match(/\s*$/)?.[0] || "";
  return `${leading}${translated}${trailing}`;
}

export function translateUiText(value: string, language: UiLanguage) {
  if (language === "english") {
    return value;
  }

  const source = String(value ?? "");
  const trimmed = source.trim();

  if (!trimmed) {
    return source;
  }

  const table = TRANSLATIONS[language];
  const exact = table[trimmed];
  if (exact) {
    return preserveWhitespace(source, exact);
  }

  let translated = trimmed;
  const fragments = FRAGMENT_TRANSLATIONS[language];

  Object.entries(fragments).forEach(([english, localized]) => {
    translated = translated.split(english).join(localized);
  });

  return translated === trimmed ? source : preserveWhitespace(source, translated);
}
