org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=true
PLACEPREP_VERSION_CODE=1
PLACEPREP_VERSION_NAME=1.0.0
PLACEPREP_APP_NAME=PlacePrep
PLACEPREP_DEBUG_APP_NAME=PlacePrep Dev
PLACEPREP_API_BASE_URL=https://placeprep-api-production-3670.up.railway.app/api/
PLACEPREP_API_BASE_URL_RELEASE=https://placeprep-api-production-3670.up.railway.app/api/
PLACEPREP_API_BASE_URL_DEBUG=https://placeprep-api-production-3670.up.railway.app/api/
