org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=true
PLACEPREP_VERSION_CODE=2
PLACEPREP_VERSION_NAME=2.0.0
PLACEPREP_APP_NAME=PlacePrep
PLACEPREP_DEBUG_APP_NAME=PlacePrep Dev
PLACEPREP_API_BASE_URL=https://placeprep-api-production-2481.up.railway.app/api/
PLACEPREP_API_BASE_URL_RELEASE=https://placeprep-api-production-2481.up.railway.app/api/
PLACEPREP_API_BASE_URL_DEBUG=https://placeprep-api-production-2481.up.railway.app/api/
